import { Creation, PrimaryComment } from './creation';

export const SILLY_ANIMATION_VIDEOS: Creation[] = [
  {
    id: "1",
    title: 'Funny videos : Funny Cartoons -  Try not to laugh or grin',
    creator_id: 4,
    youtube_id: 'sra_H9o7pjA',
    description: 'Funny videos : Funny Cartoons - Try not to laugh or grin .We update videos once a day for you to get your laughs! IKE, COMMENT ...',
    category: 'Category 3',
    comments: [],
  },
  {
    id: "2",
    title: 'CRACKÉ - UPSET STOMACH | Funny Videos For Kids | Videos For Kids | WildBrain Cartoons',
    creator_id: 7,
    youtube_id: 'kdwRWC5yc20',
    description: 'Ed must save his eggs from inside a crocodile.SUBSCRIBE for more Cracké: http://bit.ly/2zcmQxbMore about Cracké: http ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "3",
    title: 'Three Little Pigs Cartoon | Silly Crocodile Fairy Tales & Bedtime Stories for Kids | 3 Little Pigs',
    creator_id: 2,
    youtube_id: 'WhlLUvWr7Ng',
    description: 'Three Little Pigs!  Three Little Pigs!  Here’s a silly crocodile cartoon about your fairy tale Three Little Pigs story! OK ...',
    category: 'Category 2',
    comments: [],
  },
  {
    id: "4",
    title: 'Silly Symphony Lambert The Sheepish Lion',
    creator_id: 8,
    youtube_id: 'NCfaBjdh5V4',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/UgQckA You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 2',
    comments: [],
  },
  {
    id: "5",
    title: 'Animation Silly Symphony Flowers And Trees Disney Movies   Movies For Kids   Animation6',
    creator_id: 0,
    youtube_id: 'rH-OTZm0Xtk',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/LcZxEu You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 3',
    comments: [],
  },
  {
    id: "6",
    title: "WORLD'S MOST HILARIOUS FORTNITE ANIMATIONS!",
    creator_id: 3,
    youtube_id: '85n_e9XVZAM',
    description: "WORLD'S MOST HILARIOUS FORTNITE ANIMATIONS!Videos reacted to:Hybrid & the Sunny Steps | The Squad (Fortnite Animation ...",
    category: 'Category 2',
    comments: [],
  },
  {
    id: "7",
    title: 'FNaF FUNNY Try Not To Laugh Challenge 2020',
    creator: 'Creator_3',
    youtube_id: 'f5JZTvGFgV8',
    description: 'FNaF FUNNY Try Not To Laugh Challenge 2020Can you get to the end of the funny fnaf video WITHOUT laughing? Let me know now in ...',
    category: 'Category 3',
    comments: [],
  },
  {
    id: "8",
    title: 'Funny CGI 3d Animated Short Film ** BIG CATCH ** Hilarious CGI Animation Kids Cartoon by Moles Merlo',
    creator: 'Creator_2',
    youtube_id: 'Anw_bhEzsys',
    description: 'Enjoy this super funny Kids CGI 3d Animated short film THE BIG CATCH, by Imerges Studios and Moles Merlo. Featured at ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "9",
    title: 'Cartoon Box Catch Up 14 | The BEST of Cartoon Box | Hilarious Cartoon Compilation | Marilyn Monroe',
    creator: 'Creator_0',
    youtube_id: 'KXrrocvk2k4',
    description: 'SUBSCRIBE for weekly NEW Episodes! 👉 https://goo.gl/XnUgLFThis is a funny cartoon box compilation. The BEST Cartoon Box ...',
    category: 'Category 2',
    comments: [],
  },
  {
    id: "10",
    title: 'The Lion King  Silly Symphony Lambert | Disney Cartoon',
    creator: 'Creator_9',
    youtube_id: 'VvY50vOIWl8',
    description: 'Watch The Lion King Silly Symphony Lambert | Disney Cartoon.',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "11",
    title: 'Silly Symphony Flowers And Trees',
    creator: 'Creator_9',
    youtube_id: 'gjnzlj5ihkY',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/UgQckA You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "12",
    title: 'HILARIOUS ANIMATIONS To Watch When You WANT TO LAUGH!',
    creator: 'Creator_1',
    youtube_id: 'QTiaaRz93c4',
    description: 'HILARIOUS ANIMATIONS To Watch When You WANT TO LAUGH!Welcome back to more hilarious animations! These hilarious animations ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "13",
    title: 'Silly Symphonies - The Skeleton Dance',
    creator: 'Creator_1',
    youtube_id: 'vOGhAV-84iI',
    description: 'As we hear the chimes at midnight and bats flutter from a belfry; as a hound howls at the full moon and black cats brawl on the ...',
    category: 'Category 3',
    comments: [],
  },
  {
    id: "14",
    title: 'Silly Symphony Little Hiawatha',
    creator: 'Creator_7',
    youtube_id: 'PZ7D6kp8PIU',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/UgQckA You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 3',
    comments: [],
  },
  {
    id: "15",
    title: 'HILARIOUS Minecraft Animation Which Will Make You CRY Of LAUGHTER!',
    creator: 'Creator_2',
    youtube_id: 'FNApaFRSSyc',
    description: 'HILARIOUS Minecraft Animation Which Will Make You CRY Of LAUGHTER!This hilarious minecraft animation will make you cry of ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "16",
    title: 'Animation Silly Symphony Lambert The Sheepish Lion Disney Movies   Movies For Kids   A6',
    creator: 'Creator_0',
    youtube_id: 'D_gXvAUUdUQ',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/LcZxEu You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 4',
    comments: [],
  },
  {
    id: "17",
    title: 'Try Watching This HILARIOUS Animation WITHOUT Laughing!',
    creator: 'Creator_8',
    youtube_id: 'dJUhkXTjewM',
    description: 'Get the NEW merch! https://fanjoy.co/collections/KwebbelkopTry Watching This HILARIOUS Animation WITHOUT Laughing!Video ...',
    category: 'Category 4',
    comments: [],
  },
  {
    id: "19",
    title: 'MOANA | Funniest Hei Hei moments from the Disney Animated Movie',
    creator: 'Creator_3',
    youtube_id: 'X9psEx5TNTU',
    description: "Watch our compilation of the funniest HEI HEI the chicken moments from Disney's MOANA. Keep up-to-date on the latest FAMILY ...",
    category: 'Category 3',
    comments: [],
  },
  {
    id: "20",
    title: 'Animation Silly Symphony Water Babies Disney Movies   Movies For Kids   Animation Movi6',
    creator: 'Creator_8',
    youtube_id: '30OE97OtZ9E',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/LcZxEu You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 1',
    comments: [],
  },
  {
    id: "21",
    title: 'Animation Silly Symphony Little Hiawatha Disney Movies   Movies For Kids   Animation M6',
    creator: 'Creator_0',
    youtube_id: 'bulNsPAeLRQ',
    description: 'Subscribe My Channel for More & New Cartoon videos ▻▻ https://goo.gl/LcZxEu You will find nice cartoon videos, Cartoon for ...',
    category: 'Category 2',
    comments: [],    
  }
]
